#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Licencjat.Resource", IsApplication=true)]

namespace Licencjat
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Gcm.Client.Resource.String.library_name = global::Licencjat.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int buttonSize = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int colorScheme = 2130771972;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int scopeUris = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060008
			public const int common_action_bar_splitter = 2131099656;
			
			// aapt resource value: 0x7f060012
			public const int common_google_signin_btn_text_dark = 2131099666;
			
			// aapt resource value: 0x7f060009
			public const int common_google_signin_btn_text_dark_default = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_signin_btn_text_dark_disabled = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_signin_btn_text_dark_focused = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_signin_btn_text_dark_pressed = 2131099658;
			
			// aapt resource value: 0x7f060013
			public const int common_google_signin_btn_text_light = 2131099667;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_signin_btn_text_light_default = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int common_google_signin_btn_text_light_disabled = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int common_google_signin_btn_text_light_focused = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int common_google_signin_btn_text_light_pressed = 2131099662;
			
			// aapt resource value: 0x7f060014
			public const int common_plus_signin_btn_text_dark = 2131099668;
			
			// aapt resource value: 0x7f060000
			public const int common_plus_signin_btn_text_dark_default = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int common_plus_signin_btn_text_dark_disabled = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_plus_signin_btn_text_dark_focused = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int common_plus_signin_btn_text_dark_pressed = 2131099649;
			
			// aapt resource value: 0x7f060015
			public const int common_plus_signin_btn_text_light = 2131099669;
			
			// aapt resource value: 0x7f060004
			public const int common_plus_signin_btn_text_light_default = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int common_plus_signin_btn_text_light_disabled = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_plus_signin_btn_text_light_focused = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int common_plus_signin_btn_text_light_pressed = 2131099653;
			
			// aapt resource value: 0x7f060011
			public const int theme_devicedefault_background = 2131099665;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_google_signin_btn_icon_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_google_signin_btn_icon_dark_disabled = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark_focused = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_light_disabled = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light_focused = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_text_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_text_dark_disabled = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark_focused = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark_pressed = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_light_disabled = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light_focused = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light_normal = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light_pressed = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_ic_googleplayservices = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_plus_signin_btn_icon_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_plus_signin_btn_icon_dark_disabled = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_plus_signin_btn_icon_dark_focused = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_plus_signin_btn_icon_dark_normal = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_plus_signin_btn_icon_dark_pressed = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_plus_signin_btn_icon_light = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_plus_signin_btn_icon_light_disabled = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_plus_signin_btn_icon_light_focused = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_plus_signin_btn_icon_light_normal = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_plus_signin_btn_icon_light_pressed = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_plus_signin_btn_text_dark = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_plus_signin_btn_text_dark_disabled = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_plus_signin_btn_text_dark_focused = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_plus_signin_btn_text_dark_normal = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_plus_signin_btn_text_dark_pressed = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_plus_signin_btn_text_light = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_plus_signin_btn_text_light_disabled = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_plus_signin_btn_text_light_focused = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_plus_signin_btn_text_light_normal = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_plus_signin_btn_text_light_pressed = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int Icon = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int SettingsIcon = 2130837547;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int adjust_height = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int adjust_width = 2131230721;
			
			// aapt resource value: 0x7f080006
			public const int auto = 2131230726;
			
			// aapt resource value: 0x7f08000a
			public const int btn_Notifications = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int btn_SelectRates = 2131230731;
			
			// aapt resource value: 0x7f08003a
			public const int btn_okNotSettings = 2131230778;
			
			// aapt resource value: 0x7f08003d
			public const int btn_okSR = 2131230781;
			
			// aapt resource value: 0x7f08003f
			public const int checkBoxListView = 2131230783;
			
			// aapt resource value: 0x7f08003e
			public const int checkBoxesLayout = 2131230782;
			
			// aapt resource value: 0x7f080022
			public const int curr1 = 2131230754;
			
			// aapt resource value: 0x7f080027
			public const int curr2 = 2131230759;
			
			// aapt resource value: 0x7f08002c
			public const int curr3 = 2131230764;
			
			// aapt resource value: 0x7f080031
			public const int curr4 = 2131230769;
			
			// aapt resource value: 0x7f080036
			public const int curr5 = 2131230774;
			
			// aapt resource value: 0x7f08000f
			public const int dailyUpdate_DateAndTime = 2131230735;
			
			// aapt resource value: 0x7f080007
			public const int dark = 2131230727;
			
			// aapt resource value: 0x7f08001d
			public const int fifthCurrencyName = 2131230749;
			
			// aapt resource value: 0x7f08001e
			public const int fifth_DailyExRate = 2131230750;
			
			// aapt resource value: 0x7f080011
			public const int firstCurrencyName = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int first_DailyExRate = 2131230738;
			
			// aapt resource value: 0x7f08001a
			public const int fourthCurrencyName = 2131230746;
			
			// aapt resource value: 0x7f08001b
			public const int fourth_DailyExRate = 2131230747;
			
			// aapt resource value: 0x7f080003
			public const int icon_only = 2131230723;
			
			// aapt resource value: 0x7f080035
			public const int lay_currFifthPack = 2131230773;
			
			// aapt resource value: 0x7f080021
			public const int lay_currFirstPack = 2131230753;
			
			// aapt resource value: 0x7f080030
			public const int lay_currFourthPack = 2131230768;
			
			// aapt resource value: 0x7f080026
			public const int lay_currSecondPack = 2131230758;
			
			// aapt resource value: 0x7f08002b
			public const int lay_currThirdPack = 2131230763;
			
			// aapt resource value: 0x7f080024
			public const int layout_sw1 = 2131230756;
			
			// aapt resource value: 0x7f080029
			public const int layout_sw2 = 2131230761;
			
			// aapt resource value: 0x7f08002e
			public const int layout_sw3 = 2131230766;
			
			// aapt resource value: 0x7f080033
			public const int layout_sw4 = 2131230771;
			
			// aapt resource value: 0x7f080038
			public const int layout_sw5 = 2131230776;
			
			// aapt resource value: 0x7f080008
			public const int light = 2131230728;
			
			// aapt resource value: 0x7f08001c
			public const int lout_fifthR = 2131230748;
			
			// aapt resource value: 0x7f080010
			public const int lout_firstR = 2131230736;
			
			// aapt resource value: 0x7f080019
			public const int lout_fourthR = 2131230745;
			
			// aapt resource value: 0x7f080013
			public const int lout_secondR = 2131230739;
			
			// aapt resource value: 0x7f080016
			public const int lout_thirdR = 2131230742;
			
			// aapt resource value: 0x7f08001f
			public const int mLayout = 2131230751;
			
			// aapt resource value: 0x7f080002
			public const int none = 2131230722;
			
			// aapt resource value: 0x7f08000d
			public const int overRatesTitlePanel = 2131230733;
			
			// aapt resource value: 0x7f08003c
			public const int pickedCurrenciesListView = 2131230780;
			
			// aapt resource value: 0x7f080020
			public const int rLay_insideScrollview = 2131230752;
			
			// aapt resource value: 0x7f08000c
			public const int scrollView = 2131230732;
			
			// aapt resource value: 0x7f080014
			public const int secondCurrencyName = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int second_DailyExRate = 2131230741;
			
			// aapt resource value: 0x7f080004
			public const int standard = 2131230724;
			
			// aapt resource value: 0x7f080025
			public const int sw1 = 2131230757;
			
			// aapt resource value: 0x7f08002a
			public const int sw2 = 2131230762;
			
			// aapt resource value: 0x7f08002f
			public const int sw3 = 2131230767;
			
			// aapt resource value: 0x7f080034
			public const int sw4 = 2131230772;
			
			// aapt resource value: 0x7f080039
			public const int sw5 = 2131230777;
			
			// aapt resource value: 0x7f080023
			public const int textBox1 = 2131230755;
			
			// aapt resource value: 0x7f080028
			public const int textBox2 = 2131230760;
			
			// aapt resource value: 0x7f08002d
			public const int textBox3 = 2131230765;
			
			// aapt resource value: 0x7f080032
			public const int textBox4 = 2131230770;
			
			// aapt resource value: 0x7f080037
			public const int textBox5 = 2131230775;
			
			// aapt resource value: 0x7f08003b
			public const int textViewInfoRatesMenu = 2131230779;
			
			// aapt resource value: 0x7f080017
			public const int thirdCurrencyName = 2131230743;
			
			// aapt resource value: 0x7f080018
			public const int third_DailyExRate = 2131230744;
			
			// aapt resource value: 0x7f08000e
			public const int titleText_Rates = 2131230734;
			
			// aapt resource value: 0x7f080009
			public const int topButtonLPanelLayout = 2131230729;
			
			// aapt resource value: 0x7f080005
			public const int wide = 2131230725;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public const int google_play_services_version = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int NotificationSettingsLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int SelectedCurrenciesLayout = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040020
			public const int ApplicationName = 2130968608;
			
			// aapt resource value: 0x7f040001
			public const int auth_google_play_services_client_facebook_display_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int auth_google_play_services_client_google_display_name = 2130968576;
			
			// aapt resource value: 0x7f040018
			public const int common_google_play_services_api_unavailable_text = 2130968600;
			
			// aapt resource value: 0x7f04000a
			public const int common_google_play_services_enable_button = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int common_google_play_services_enable_text = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int common_google_play_services_enable_title = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int common_google_play_services_install_button = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int common_google_play_services_install_text_phone = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int common_google_play_services_install_text_tablet = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int common_google_play_services_install_title = 2130968580;
			
			// aapt resource value: 0x7f040013
			public const int common_google_play_services_invalid_account_text = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int common_google_play_services_invalid_account_title = 2130968594;
			
			// aapt resource value: 0x7f040011
			public const int common_google_play_services_network_error_text = 2130968593;
			
			// aapt resource value: 0x7f040010
			public const int common_google_play_services_network_error_title = 2130968592;
			
			// aapt resource value: 0x7f040003
			public const int common_google_play_services_notification_ticker = 2130968579;
			
			// aapt resource value: 0x7f04001c
			public const int common_google_play_services_restricted_profile_text = 2130968604;
			
			// aapt resource value: 0x7f04001b
			public const int common_google_play_services_restricted_profile_title = 2130968603;
			
			// aapt resource value: 0x7f04001a
			public const int common_google_play_services_sign_in_failed_text = 2130968602;
			
			// aapt resource value: 0x7f040019
			public const int common_google_play_services_sign_in_failed_title = 2130968601;
			
			// aapt resource value: 0x7f040002
			public const int common_google_play_services_unknown_issue = 2130968578;
			
			// aapt resource value: 0x7f040015
			public const int common_google_play_services_unsupported_text = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int common_google_play_services_unsupported_title = 2130968596;
			
			// aapt resource value: 0x7f040016
			public const int common_google_play_services_update_button = 2130968598;
			
			// aapt resource value: 0x7f04000c
			public const int common_google_play_services_update_text = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int common_google_play_services_update_title = 2130968587;
			
			// aapt resource value: 0x7f04000f
			public const int common_google_play_services_updating_text = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int common_google_play_services_updating_title = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int common_google_play_services_wear_update_text = 2130968589;
			
			// aapt resource value: 0x7f040017
			public const int common_open_on_phone = 2130968599;
			
			// aapt resource value: 0x7f04001d
			public const int common_signin_button_text = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int common_signin_button_text_long = 2130968606;
			
			// aapt resource value: 0x7f040021
			public const int dateOfUpdateMain = 2130968609;
			
			// aapt resource value: 0x7f04001f
			public const int library_name = 2130968607;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Custom = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] SignInButton = new int[] {
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
